/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.trindade.app.contract.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param description 
 * @param licensePlate 
 * @param isActive 
 * @param createdAt 
 */
@Serializable

data class AdminVehicle (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "description")
    val description: kotlin.String,

    @SerialName(value = "license_plate")
    val licensePlate: kotlin.String,

    @SerialName(value = "is_active")
    val isActive: kotlin.Int,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String

) {


}

