/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.trindade.app.contract.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param categoryId 
 * @param namePt 
 * @param nameEs 
 * @param temperatureReadings 
 * @param isActive 
 * @param createdByUserId 
 * @param createdAt 
 * @param taskType 
 */
@Serializable

data class AdminTaskResponseTask (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "category_id")
    val categoryId: kotlin.Int,

    @SerialName(value = "name_pt")
    val namePt: kotlin.String,

    @SerialName(value = "name_es")
    val nameEs: kotlin.String,

    @SerialName(value = "temperature_readings")
    val temperatureReadings: kotlin.Int,

    @SerialName(value = "is_active")
    val isActive: kotlin.Int,

    @SerialName(value = "created_by_user_id")
    val createdByUserId: kotlin.Int?,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    @SerialName(value = "task_type")
    val taskType: AdminTaskResponseTask.TaskType

) {

    /**
     * 
     *
     * Values: check,temperature,check_assai,check_normal
     */
    @Serializable
    enum class TaskType(val value: kotlin.String) {
        @SerialName(value = "check") check("check"),
        @SerialName(value = "temperature") temperature("temperature"),
        @SerialName(value = "check_assai") check_assai("check_assai"),
        @SerialName(value = "check_normal") check_normal("check_normal");
    }

}

