/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.trindade.app.contract.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param userId 
 * @param displayName 
 * @param action 
 * @param entityType 
 * @param entityId 
 * @param ipAddress 
 * @param details 
 * @param createdAt 
 */
@Serializable

data class AuditLog (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "user_id")
    val userId: kotlin.Int?,

    @SerialName(value = "display_name")
    val displayName: kotlin.String?,

    @SerialName(value = "action")
    val action: kotlin.String,

    @SerialName(value = "entity_type")
    val entityType: kotlin.String,

    @SerialName(value = "entity_id")
    val entityId: kotlin.Int?,

    @SerialName(value = "ip_address")
    val ipAddress: kotlin.String?,

    @SerialName(value = "details")
    val details: kotlin.String?,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String

) {


}

