/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.trindade.app.contract.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param taskId 
 * @param checked 
 * @param selectedProducts 
 */
@Serializable

data class CreateReportRequestItemsInner (

    @SerialName(value = "taskId")
    val taskId: kotlin.Int,

    @SerialName(value = "checked")
    val checked: kotlin.Boolean,

    @SerialName(value = "selectedProducts")
    val selectedProducts: kotlin.collections.List<kotlin.String>? = null

) {


}

