/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.trindade.app.contract.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param username 
 * @param password 
 * @param displayName 
 * @param roleId 
 */
@Serializable

data class CreateAdminUserRequest (

    @SerialName(value = "username")
    val username: kotlin.String,

    @SerialName(value = "password")
    val password: kotlin.String,

    @SerialName(value = "display_name")
    val displayName: kotlin.String,

    @SerialName(value = "role_id")
    val roleId: CreateAdminUserRequest.RoleId

) {

    /**
     * 
     *
     * Values: _1,_2
     */
    @Serializable
    enum class RoleId(val value: kotlin.Int) {
        @SerialName(value = "1") _1(1),
        @SerialName(value = "2") _2(2);
    }

}

