/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.trindade.app.contract.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param parentCategoryId 
 * @param namePt 
 * @param nameEs 
 * @param categoryType 
 * @param sortOrder 
 */
@Serializable

data class CreateAdminCategoryRequest (

    @SerialName(value = "parent_category_id")
    val parentCategoryId: kotlin.Int? = null,

    @SerialName(value = "name_pt")
    val namePt: kotlin.String? = null,

    @SerialName(value = "name_es")
    val nameEs: kotlin.String? = null,

    @SerialName(value = "category_type")
    val categoryType: CreateAdminCategoryRequest.CategoryType? = CategoryType.check,

    @SerialName(value = "sort_order")
    val sortOrder: kotlin.Int? = 0

) {

    /**
     * 
     *
     * Values: check,temperature,check_assai,check_normal
     */
    @Serializable
    enum class CategoryType(val value: kotlin.String) {
        @SerialName(value = "check") check("check"),
        @SerialName(value = "temperature") temperature("temperature"),
        @SerialName(value = "check_assai") check_assai("check_assai"),
        @SerialName(value = "check_normal") check_normal("check_normal");
    }

}

