/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.trindade.app.contract.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param scheduleDate 
 * @param timeSlot 
 * @param driverType 
 * @param driverId 
 * @param vehicleId 
 */
@Serializable

data class CreateScheduleRequest (

    @SerialName(value = "schedule_date")
    val scheduleDate: kotlin.String,

    @SerialName(value = "time_slot")
    val timeSlot: kotlin.String,

    @SerialName(value = "driver_type")
    val driverType: CreateScheduleRequest.DriverType,

    @SerialName(value = "driver_id")
    val driverId: kotlin.Int,

    @SerialName(value = "vehicle_id")
    val vehicleId: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: fletero,casa
     */
    @Serializable
    enum class DriverType(val value: kotlin.String) {
        @SerialName(value = "fletero") fletero("fletero"),
        @SerialName(value = "casa") casa("casa");
    }

}

