/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.trindade.app.contract.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param categoryId 
 * @param namePt 
 * @param nameEs 
 * @param temperatureReadings 
 */
@Serializable

data class CreateAdminTaskRequest (

    @SerialName(value = "category_id")
    val categoryId: kotlin.Int,

    @SerialName(value = "name_pt")
    val namePt: kotlin.String? = null,

    @SerialName(value = "name_es")
    val nameEs: kotlin.String? = null,

    @SerialName(value = "temperature_readings")
    val temperatureReadings: kotlin.Int? = 1

) {


}

