/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.trindade.app.contract.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param reportsToday 
 * @param schedulesTomorrow 
 * @param activeUsers 
 * @param reportsTotal 
 * @param schedulesTotal 
 * @param latestReportId 
 * @param higieneDone 
 * @param higieneTotal 
 * @param recepcionDone 
 * @param recepcionTotal 
 */
@Serializable

data class DashboardSummary (

    @SerialName(value = "reportsToday")
    val reportsToday: kotlin.Int,

    @SerialName(value = "schedulesTomorrow")
    val schedulesTomorrow: kotlin.Int,

    @SerialName(value = "activeUsers")
    val activeUsers: kotlin.Int,

    @SerialName(value = "reportsTotal")
    val reportsTotal: kotlin.Int,

    @SerialName(value = "schedulesTotal")
    val schedulesTotal: kotlin.Int,

    @SerialName(value = "latestReportId")
    val latestReportId: kotlin.Int?,

    @SerialName(value = "higieneDone")
    val higieneDone: kotlin.Int,

    @SerialName(value = "higieneTotal")
    val higieneTotal: kotlin.Int,

    @SerialName(value = "recepcionDone")
    val recepcionDone: kotlin.Int,

    @SerialName(value = "recepcionTotal")
    val recepcionTotal: kotlin.Int

) {


}

