/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.trindade.app.contract.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param licensePlate 
 * @param driverType 
 */
@Serializable

data class Driver (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "license_plate")
    val licensePlate: kotlin.String?,

    @SerialName(value = "driver_type")
    val driverType: Driver.DriverType

) {

    /**
     * 
     *
     * Values: casa,fletero
     */
    @Serializable
    enum class DriverType(val value: kotlin.String) {
        @SerialName(value = "casa") casa("casa"),
        @SerialName(value = "fletero") fletero("fletero");
    }

}

