/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.trindade.app.contract.models

import com.trindade.app.contract.models.ScheduleCreator

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param batchDate 
 * @param loadingDate 
 * @param totalLoadings 
 * @param createdAt 
 * @param updatedAt 
 * @param isActive 
 * @param canEdit 
 * @param canDeactivate 
 * @param canDelete 
 * @param readOnly 
 * @param creator 
 */
@Serializable

data class LoadingBatchHistoryItem (

    @SerialName(value = "batch_date")
    val batchDate: kotlin.String,

    @SerialName(value = "loading_date")
    val loadingDate: kotlin.String,

    @SerialName(value = "total_loadings")
    val totalLoadings: kotlin.Int,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String?,

    @SerialName(value = "updated_at")
    val updatedAt: kotlin.String?,

    @SerialName(value = "isActive")
    val isActive: kotlin.Boolean,

    @SerialName(value = "canEdit")
    val canEdit: kotlin.Boolean,

    @SerialName(value = "canDeactivate")
    val canDeactivate: kotlin.Boolean,

    @SerialName(value = "canDelete")
    val canDelete: kotlin.Boolean,

    @SerialName(value = "readOnly")
    val readOnly: kotlin.Boolean,

    @SerialName(value = "creator")
    val creator: ScheduleCreator?

) {


}

