/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.trindade.app.contract.models

import com.trindade.app.contract.models.LoginResponseUser

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param token 
 * @param refreshToken 
 * @param expiresIn 
 * @param user 
 */
@Serializable

data class LoginResponse (

    @SerialName(value = "token")
    val token: kotlin.String,

    @SerialName(value = "refreshToken")
    val refreshToken: kotlin.String,

    @SerialName(value = "expiresIn")
    val expiresIn: kotlin.Int,

    @SerialName(value = "user")
    val user: LoginResponseUser

) {


}

