/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.trindade.app.contract.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param reportId 
 * @param filePath 
 * @param fileSize 
 * @param mimeType 
 * @param publicToken 
 * @param createdAt 
 * @param url 
 * @param publicUrl 
 */
@Serializable

data class PhotosResponsePhotosInner (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "report_id")
    val reportId: kotlin.Int,

    @SerialName(value = "file_path")
    val filePath: kotlin.String,

    @SerialName(value = "file_size")
    val fileSize: kotlin.Int,

    @SerialName(value = "mime_type")
    val mimeType: kotlin.String,

    @SerialName(value = "public_token")
    val publicToken: kotlin.String,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    @SerialName(value = "url")
    val url: kotlin.String? = null,

    @SerialName(value = "publicUrl")
    val publicUrl: kotlin.String? = null

) {


}

