/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.trindade.app.contract.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param assai 
 * @param normal 
 */
@Serializable

data class ProductsResponse (

    @SerialName(value = "assai")
    val assai: kotlin.collections.List<ProductsResponse.Assai>,

    @SerialName(value = "normal")
    val normal: kotlin.collections.List<ProductsResponse.Normal>

) {

    /**
     * 
     *
     * Values: Nhoque_Kg,Quadrada,Rolo_500,Rolo_kg,Rolo_2kg,Lashana,Disco_200g,Disco_400g,Disgo_500g
     */
    @Serializable
    enum class Assai(val value: kotlin.String) {
        @SerialName(value = "Nhoque Kg") Nhoque_Kg("Nhoque Kg"),
        @SerialName(value = "Quadrada") Quadrada("Quadrada"),
        @SerialName(value = "Rolo 500") Rolo_500("Rolo 500"),
        @SerialName(value = "Rolo kg") Rolo_kg("Rolo kg"),
        @SerialName(value = "Rolo 2kg") Rolo_2kg("Rolo 2kg"),
        @SerialName(value = "Lashana") Lashana("Lashana"),
        @SerialName(value = "Disco 200g") Disco_200g("Disco 200g"),
        @SerialName(value = "Disco 400g") Disco_400g("Disco 400g"),
        @SerialName(value = "Disgo 500g") Disgo_500g("Disgo 500g");
    }
    /**
     * 
     *
     * Values: Nhoque_400g,Nhoque_Kg,Quadrada
     */
    @Serializable
    enum class Normal(val value: kotlin.String) {
        @SerialName(value = "Nhoque 400g") Nhoque_400g("Nhoque 400g"),
        @SerialName(value = "Nhoque Kg") Nhoque_Kg("Nhoque Kg"),
        @SerialName(value = "Quadrada") Quadrada("Quadrada");
    }

}

