/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.trindade.app.contract.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param location 
 * @param locationEs 
 * @param readingIndex 
 * @param `value` 
 */
@Serializable

data class ReportDetailTemperaturesInner (

    @SerialName(value = "location")
    val location: kotlin.String,

    @SerialName(value = "location_es")
    val locationEs: kotlin.String?,

    @SerialName(value = "readingIndex")
    val readingIndex: kotlin.Int,

    @Contextual @SerialName(value = "value")
    val `value`: java.math.BigDecimal

) {


}

