/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.trindade.app.contract.models

import com.trindade.app.contract.models.ReportDetailItemsInner
import com.trindade.app.contract.models.ReportDetailTemperaturesInner
import com.trindade.app.contract.models.ReportListItemUser

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param turno 
 * @param reportDate 
 * @param notes 
 * @param createdAt 
 * @param user 
 * @param updatedAt 
 * @param items 
 * @param temperatures 
 * @param isActive 
 * @param readOnly 
 * @param canEdit 
 * @param canDeactivate 
 * @param canDelete 
 */
@Serializable

data class ReportResponseReport (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "turno")
    val turno: ReportResponseReport.Turno,

    @SerialName(value = "report_date")
    val reportDate: kotlin.String,

    @SerialName(value = "notes")
    val notes: kotlin.String?,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    @SerialName(value = "user")
    val user: ReportListItemUser,

    @SerialName(value = "updated_at")
    val updatedAt: kotlin.String,

    @SerialName(value = "items")
    val items: kotlin.collections.List<ReportDetailItemsInner>,

    @SerialName(value = "temperatures")
    val temperatures: kotlin.collections.List<ReportDetailTemperaturesInner>,

    @SerialName(value = "isActive")
    val isActive: kotlin.Boolean? = null,

    @SerialName(value = "readOnly")
    val readOnly: kotlin.Boolean? = null,

    @SerialName(value = "canEdit")
    val canEdit: kotlin.Boolean? = null,

    @SerialName(value = "canDeactivate")
    val canDeactivate: kotlin.Boolean? = null,

    @SerialName(value = "canDelete")
    val canDelete: kotlin.Boolean? = null

) {

    /**
     * 
     *
     * Values: tarde,noite
     */
    @Serializable
    enum class Turno(val value: kotlin.String) {
        @SerialName(value = "tarde") tarde("tarde"),
        @SerialName(value = "noite") noite("noite");
    }

}

