/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.trindade.app.contract.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param taskId 
 * @param taskName 
 * @param taskNameEs 
 * @param taskType 
 * @param categoryName 
 * @param categoryNameEs 
 * @param checked 
 * @param selectedProducts 
 */
@Serializable

data class ReportItemDetail (

    @SerialName(value = "task_id")
    val taskId: kotlin.Int,

    @SerialName(value = "task_name")
    val taskName: kotlin.String,

    @SerialName(value = "task_name_es")
    val taskNameEs: kotlin.String,

    @SerialName(value = "task_type")
    val taskType: ReportItemDetail.TaskType,

    @SerialName(value = "category_name")
    val categoryName: kotlin.String,

    @SerialName(value = "category_name_es")
    val categoryNameEs: kotlin.String,

    @SerialName(value = "checked")
    val checked: kotlin.Boolean,

    @SerialName(value = "selectedProducts")
    val selectedProducts: kotlin.collections.List<kotlin.String>? = null

) {

    /**
     * 
     *
     * Values: check,temperature,check_assai,check_normal
     */
    @Serializable
    enum class TaskType(val value: kotlin.String) {
        @SerialName(value = "check") check("check"),
        @SerialName(value = "temperature") temperature("temperature"),
        @SerialName(value = "check_assai") check_assai("check_assai"),
        @SerialName(value = "check_normal") check_normal("check_normal");
    }

}

