/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.trindade.app.contract.models

import com.trindade.app.contract.models.ScheduleHistoryResponseItemsInner
import com.trindade.app.contract.models.ScheduleHistoryResponsePagination

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param items 
 * @param pagination 
 */
@Serializable

data class ScheduleHistoryResponse (

    @SerialName(value = "items")
    val items: kotlin.collections.List<ScheduleHistoryResponseItemsInner>,

    @SerialName(value = "pagination")
    val pagination: ScheduleHistoryResponsePagination

) {


}

