/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.trindade.app.contract.models

import com.trindade.app.contract.models.ScheduleCreator

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param scheduleDate 
 * @param timeSlot 
 * @param driverType 
 * @param driverId 
 * @param driverName 
 * @param licensePlate 
 * @param vehicleId 
 * @param vehicleDescription 
 * @param vehiclePlate 
 * @param userId 
 * @param createdAt 
 * @param updatedAt 
 * @param isActive 
 * @param creatorName 
 * @param isActive 
 * @param readOnly 
 * @param canEdit 
 * @param canDeactivate 
 * @param canDelete 
 * @param creator 
 */
@Serializable

data class Schedule (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "schedule_date")
    val scheduleDate: kotlin.String,

    @SerialName(value = "time_slot")
    val timeSlot: kotlin.String,

    @SerialName(value = "driver_type")
    val driverType: Schedule.DriverType,

    @SerialName(value = "driver_id")
    val driverId: kotlin.Int?,

    @SerialName(value = "driver_name")
    val driverName: kotlin.String?,

    @SerialName(value = "license_plate")
    val licensePlate: kotlin.String?,

    @SerialName(value = "vehicle_id")
    val vehicleId: kotlin.Int?,

    @SerialName(value = "vehicle_description")
    val vehicleDescription: kotlin.String?,

    @SerialName(value = "vehicle_plate")
    val vehiclePlate: kotlin.String?,

    @SerialName(value = "user_id")
    val userId: kotlin.Int?,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    @SerialName(value = "updated_at")
    val updatedAt: kotlin.String,

    @SerialName(value = "is_active")
    val isActive: kotlin.Int,

    @SerialName(value = "creator_name")
    val creatorName: kotlin.String?,

    @SerialName(value = "isActive")
    val isActive: kotlin.Boolean,

    @SerialName(value = "readOnly")
    val readOnly: kotlin.Boolean,

    @SerialName(value = "canEdit")
    val canEdit: kotlin.Boolean,

    @SerialName(value = "canDeactivate")
    val canDeactivate: kotlin.Boolean,

    @SerialName(value = "canDelete")
    val canDelete: kotlin.Boolean,

    @SerialName(value = "creator")
    val creator: ScheduleCreator?

) {

    /**
     * 
     *
     * Values: fletero,casa
     */
    @Serializable
    enum class DriverType(val value: kotlin.String) {
        @SerialName(value = "fletero") fletero("fletero"),
        @SerialName(value = "casa") casa("casa");
    }

}

