/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.trindade.app.contract.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param success 
 * @param userId 
 */
@Serializable

data class SetupResponse (

    @SerialName(value = "success")
    val success: SetupResponse.Success,

    @SerialName(value = "userId")
    val userId: kotlin.Int

) {

    /**
     * 
     *
     * Values: `true`
     */
    @Serializable
    enum class Success(val value: kotlin.Boolean) {
        @SerialName(value = "true") `true`(true);
    }

}

