/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.trindade.app.contract.models

import com.trindade.app.contract.models.CreateReportRequestItemsInner
import com.trindade.app.contract.models.CreateReportRequestTemperaturesInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param turno 
 * @param notes 
 * @param items 
 * @param temperatures 
 */
@Serializable

data class UpdateReportRequest (

    @SerialName(value = "turno")
    val turno: UpdateReportRequest.Turno? = null,

    @SerialName(value = "notes")
    val notes: kotlin.String? = null,

    @SerialName(value = "items")
    val items: kotlin.collections.List<CreateReportRequestItemsInner>? = null,

    @SerialName(value = "temperatures")
    val temperatures: kotlin.collections.List<CreateReportRequestTemperaturesInner>? = null

) {

    /**
     * 
     *
     * Values: tarde,noite
     */
    @Serializable
    enum class Turno(val value: kotlin.String) {
        @SerialName(value = "tarde") tarde("tarde"),
        @SerialName(value = "noite") noite("noite");
    }

}

