/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.trindade.app.contract.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param username 
 * @param password 
 * @param displayName 
 * @param roleId 
 * @param isActive 
 */
@Serializable

data class UpdateAdminUserRequest (

    @SerialName(value = "username")
    val username: kotlin.String? = null,

    @SerialName(value = "password")
    val password: kotlin.String? = null,

    @SerialName(value = "display_name")
    val displayName: kotlin.String? = null,

    @SerialName(value = "role_id")
    val roleId: UpdateAdminUserRequest.RoleId? = null,

    @SerialName(value = "is_active")
    val isActive: UpdateAdminUserRequest.IsActive? = null

) {

    /**
     * 
     *
     * Values: _1,_2
     */
    @Serializable
    enum class RoleId(val value: kotlin.Int) {
        @SerialName(value = "1") _1(1),
        @SerialName(value = "2") _2(2);
    }
    /**
     * 
     *
     * Values: _0,_1
     */
    @Serializable
    enum class IsActive(val value: kotlin.Int) {
        @SerialName(value = "0") _0(0),
        @SerialName(value = "1") _1(1);
    }

}

