/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.trindade.app.contract.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param description 
 * @param licensePlate 
 * @param isActive 
 */
@Serializable

data class UpdateAdminVehicleRequest (

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "license_plate")
    val licensePlate: kotlin.String? = null,

    @SerialName(value = "is_active")
    val isActive: UpdateAdminVehicleRequest.IsActive? = null

) {

    /**
     * 
     *
     * Values: _0,_1
     */
    @Serializable
    enum class IsActive(val value: kotlin.Int) {
        @SerialName(value = "0") _0(0),
        @SerialName(value = "1") _1(1);
    }

}

