/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.trindade.app.contract.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param categoryId 
 * @param namePt 
 * @param nameEs 
 * @param isActive 
 * @param temperatureReadings 
 */
@Serializable

data class UpdateAdminTaskRequest (

    @SerialName(value = "category_id")
    val categoryId: kotlin.Int? = null,

    @SerialName(value = "name_pt")
    val namePt: kotlin.String? = null,

    @SerialName(value = "name_es")
    val nameEs: kotlin.String? = null,

    @SerialName(value = "is_active")
    val isActive: UpdateAdminTaskRequest.IsActive? = null,

    @SerialName(value = "temperature_readings")
    val temperatureReadings: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: _0,_1
     */
    @Serializable
    enum class IsActive(val value: kotlin.Int) {
        @SerialName(value = "0") _0(0),
        @SerialName(value = "1") _1(1);
    }

}

