plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    // The serialization compiler plugin, which D1 was missing. kotlinx-serialization-json alone is the
    // runtime: without this plugin a @Serializable class compiles and then fails at the first encode
    // or decode, because no serializer was ever generated for it. The contract types are all
    // @Serializable, so this is what makes them usable rather than merely present.
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
}

android {
    namespace = "com.trindade.app"
    // The pinned androidx/OkHttp versions (Compose 1.12.x, OkHttp 5.5.0) require API 37;
    // compileSdk is build-time only and stays independent of the targetSdk product floor.
    compileSdk = 37

    defaultConfig {
        applicationId = "com.trindade.app"
        // Android 8.0 is a deliberate floor: field devices still on Oreo remain common.
        minSdk = 26
        targetSdk = 35
        versionCode = 1
        versionName = "0.1.0"

        // The base URL is configuration, never a constant: the same build must be able to point at a
        // deployment that does not exist yet. The default targets the emulator host loopback, which
        // is the one cleartext host the debug network security config exempts.
        //
        // The value is validated rather than accepted, because every failure mode here is silent:
        // a URL without a scheme or without its trailing slash compiles, installs, and then fails
        // at runtime inside Retrofit with an error that does not name the cause. Checking it here
        // turns that into a configuration failure.
        val apiBaseUrl = (project.findProperty("apiBaseUrl") as String?) ?: "http://10.0.2.2:3000/"
        require(apiBaseUrl.startsWith("http://") || apiBaseUrl.startsWith("https://")) {
            "apiBaseUrl must be an absolute http(s) URL, but was '$apiBaseUrl'."
        }
        require(apiBaseUrl.endsWith("/")) {
            "apiBaseUrl must end with '/', because Retrofit resolves every endpoint relative to it. " +
                "Got '$apiBaseUrl'."
        }
        buildConfigField("String", "API_BASE_URL", "\"$apiBaseUrl\"")
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    // The contract artifact is the single source of truth for the paths this client speaks, and the
    // test that checks the interfaces against it reads it from the test classpath. Pointing the test
    // resources at the package avoids a copy step and any chance of the copy going stale.
    sourceSets["test"].resources.srcDir(rootProject.file("../contracts"))

    // The contract types live in packages/android/contract, generated by
    // scripts/generate-android-contract.sh and committed. Wired in as a source directory rather than
    // as a Gradle module so the generated tree stays out of the application's own layout, and so the
    // module root is never the generator's output directory -- it writes a gradle/wrapper/ of its own
    // and would overwrite this module's.
    //
    // Resolved through rootProject because a bare relative path here is relative to this module, i.e.
    // packages/android/app/, which made it point at a directory that does not exist. Gradle ignores a
    // source directory that is not there, so the generated types were silently NOT compiled and this
    // lane stayed green until something finally referenced one of them.
    sourceSets["main"].kotlin.srcDir(rootProject.file("contract/src/main/kotlin"))

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
    }
}

// A release build must carry an https base URL, and there is deliberately no default: shipping
// against the emulator loopback is not a configuration anyone chooses on purpose, so it fails here
// rather than on a user's device, where the release manifest grants no cleartext exception and the
// request could not succeed anyway.
//
// The guard hangs off generateReleaseBuildConfig rather than off the tasks that consume the value,
// and the placement is the whole point. Two earlier placements were wrong in instructive ways. A
// require in the android block ran at configuration time, and because AGP configures every build
// type before running any task, it broke assembleDebug while trying to guard the release build.
// Matching the task names assembleRelease and bundleRelease fixed that but left every other release
// producer unguarded: packageReleaseBundle, packageRelease, packageReleaseUniversalApk, and any
// flavoured variant assembled under a name nobody predicted.
//
// Every task that produces a release artifact must generate BuildConfig first, so a guard here
// cannot be bypassed by choosing a different entry point, and it sits on the very task that
// produces the value being checked. The remaining assumption is worth stating: this depends on
// BuildConfig being generated, so turning off buildFeatures.buildConfig would silently remove it.
val declaredApiBaseUrl = (project.findProperty("apiBaseUrl") as String?) ?: ""
tasks.matching {
    it.name.startsWith("generate") && it.name.endsWith("BuildConfig") && it.name.contains("Release")
}.configureEach {
    doFirst {
        require(declaredApiBaseUrl.isNotEmpty()) {
            "A release build requires -PapiBaseUrl=https://<host>/. There is no default, so that a " +
                "release can never silently point at the development loopback."
        }
        require(declaredApiBaseUrl.startsWith("https://")) {
            "A release build requires an https apiBaseUrl, but got '$declaredApiBaseUrl'."
        }
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.hilt.navigation.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.material3)

    implementation(libs.hilt.android)
    ksp(libs.hilt.compiler)

    implementation(libs.retrofit)
    implementation(libs.retrofit.converter.kotlinx.serialization)
    implementation(libs.okhttp)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.kotlinx.coroutines.android)

    testImplementation(libs.junit)
    testImplementation(libs.mockwebserver)
    testImplementation(libs.kotlinx.coroutines.test)
}
